### ISSUE TITLE
Dropdown Selector for Posts

### ISSUE THREAD

**Issue by johncionci** [oomphinc/WP-Forms-API#26]
Would be nice to have a simple selector like 'postfield' that displays a dropdown list of all posts.
This would be useful when building meta fields that will include linking to a post instead of external resource.

**Comment by bendoh** [comment]
There is a `post_select` type that you can use which implements exactly this, however it's not a drop-down, it's more of a search UI element.

**Comment by balbuf** [comment]
It would be nice if that element did show results upon focusing though - so that you don't necessarily need to know the exact name of the post.
