### ISSUE TITLE
example form snippet

### ISSUE THREAD

**Issue by illucent** [oomphinc/WP-Forms-API#3]
hi! cool API!
Can You please provide full form example snippet which starts with

``` html
<form....
```

and ends with 

``` html
form>
```

i am interested in 

``` html
<form action="?"
```

field example

**Comment by bendoh** [comment]
Thanks. I have added an example to the README as well as an [example code snippet](https://github.com/oomphinc/WP-Forms-API/blob/master/examples/simple.php).  Please let me know if this helps.
